export default{
	showLoading:({commit})=>{
		commit('showLoading')
	},
	hideLoading:({commit})=>{
		commit('hideLoading')
	},
	showStarDtl1:({commit})=>{
		commit('showStarDtl1')
	},
	hideStarDtl1:({commit})=>{
		commit('hideStarDtl1')
	},
	showStarDtl2:({commit})=>{
		commit('showStarDtl2')
	},
	hideStarDtl2:({commit})=>{
		commit('hideStarDtl2')
	},
	showStarSel1:({commit})=>{
		commit('showStarSel1')
	},
	hideStarSel1:({commit})=>{
		commit('hideStarSel1')
	},
	showStarSel2:({commit})=>{
		commit('showStarSel2')
	},
	hideStarSel2:({commit})=>{
		commit('hideStarSel2')
	},
}